name: another-Build

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  update-code:
    name: Update Code
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.HEAD_REF }}
          #token: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Install Node.js
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version: 20.17.0

      - name: npm – Install Dependencies
        run: npm ci