name: another-Build

on:
  pull_request:
    branches:
      - main
jobs:
  pr-test:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
    steps:
      - run: echo ${{ github.repository_owner }}
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - run: git push origin ${{ github.head_ref }}
      - name: Set up Node
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af
        with:
          node-version: 20.17.0
      - run: npm install